const fs = require('fs');
const vm = require('vm');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..');
const sandbox = { console, setTimeout, clearTimeout(){}, alert(){}, confirm(){return true;}, showToast(){}, saveCharacter: async()=>{}, db:{characters:[]}, document:{getElementById(){return null;}} };
sandbox.window=sandbox; vm.createContext(sandbox);
for (const file of ['js/features/memory_v3/memory_core_v3.js','js/features/memory_v3/memory_rounds_v3.js','js/features/memory_v3/memory_engine_v3.js']) vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'), sandbox,{filename:file});
const M=sandbox.MemoryV5; const chat={id:'c',history:[]}; sandbox.db.characters.push(chat); const store=M.model.ensureStore(chat);
let r=M.engine.applyOperations(chat,[{tableId:'v5_recent_events',action:'add',values:{分类:'生活',标题:'测试事项',内容:'测试事项已经完成',事项状态:'已完结',结果:'完成'}}],{origin:'manual'});
assert.equal(r.changed.length,1);
const sourceId=r.changed[0].recordId;
const draft=M.engine.buildSummaryDraft(chat,'v5_recent_events',[sourceId]);
assert.equal(draft.targetTable.id,'v5_event_summary');
assert(draft.values.内容.includes('测试事项'));
(async()=>{
 const report=await M.engine.runAggregation(chat,'v5_recent_events',[sourceId],draft.values);
 assert.equal(report.sourceCount,1);
 const source=store.records.v5_recent_events.find(x=>x.id===sourceId);
 assert(source.compressedAt && source.compressedBy);
 assert.equal(store.records.v5_event_summary.length,1);
 const ctx=M.engine.getContextBlock(chat);
 assert(!ctx.includes('测试事项已经完成'),'已压缩短期记录不得继续进入上下文');
 const summaryId=store.records.v5_event_summary[0].id;
 const longDraft=M.engine.buildLongTermDraft(chat,'v5_event_summary',[summaryId]);
 assert.equal(longDraft.targetTable.id,'v5_stable_long_term');
 assert(longDraft.values.内容.includes('近期事项总结'));
 longDraft.values.分类='稳定能力';
 longDraft.values.标题='完成事项习惯';
 longDraft.values.内容='用户会把明确事项推进到完成，并在结束后记录结果。';
 longDraft.values.长期类型='稳定能力';
 const longReport=await M.engine.saveLongTermDraft(chat,'v5_event_summary',[summaryId],longDraft.values);
 assert.equal(longReport.changed.length,1);
 assert.equal(store.records.v5_stable_long_term.length,1);
 const del=await M.engine.deleteCompressed(chat,'v5_recent_events');
 assert.equal(del.deleted,1);
 assert.equal(store.records.v5_recent_events.length,0);
 assert.equal(store.records.v5_event_summary.length,1);
 assert.equal(store.records.v5_stable_long_term.length,1);
 console.log('Memory V5.2 compression and long-term draft tests passed');
})().catch(e=>{console.error(e);process.exit(1)});
