const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');

assert(['2.13-R1', '2.13-R4', '2.13-R5', '2.13-R5.1', '2.13-R5.2', '2.13-R5.3', '2.13-R5.4', '2.14-R0', '2.14-R1', '2.14-R2', '2.14-R3', '2.14-R4', '2.14-R5', '2.14-R6', '2.14-R7', '2.14-R8', '2.14-R8.1'].includes(read('VERSION.txt').trim()));
const dock = read('js/modules/floating_ball.js');
const barSource = read('js/modules/quick_dock_action_bar.js');
const css = read('css/modules/quick_dock.css');
const html = read('index.html');

assert(html.includes('js/modules/quick_dock_action_bar.js'));
assert(html.indexOf('quick_dock_action_bar.js') < html.indexOf('floating_ball.js'));
assert(dock.includes("const REPORT_MODE = 'detailed'"));
assert(!dock.includes('set-view-mode'));
assert(!dock.includes('quick-dock-view-mode-bar'));
assert(!dock.includes("open-proment-full"));
assert(!dock.includes('在 Proment 核对'));
assert(dock.includes('renderPanelShell'));
assert(dock.includes('quick-dock-top-model-select'));
assert(css.includes('.quick-dock-action-hub'));
assert(css.includes('.quick-dock-top-actions'));
assert(css.includes('grid-template-columns:repeat(3,minmax(0,1fr))'));

const context = { window: {} };
vm.createContext(context);
vm.runInContext(barSource, context);
const bar = context.window.QuickDockActionBar;
assert(bar);
assert.strictEqual(bar.VERSION, '2.13-R1');
assert.strictEqual(bar.ACTIONS.length, 6);
const markup = bar.render({ activePanel: 'operation', api: { provider: 'newapi', model: 'test-model' }, operationId: 'op-1' });
['操作记录','日志','覆盖','Git 上传','Git 恢复','Git 设置'].forEach(label => assert(markup.includes(label)));
['详情','Proment'].forEach(label => assert(!markup.includes(`>${label}<`)));
assert(markup.includes('data-qd-action="main" aria-current="page"'));
assert(markup.includes('quick-dock-top-model-select'));
assert(markup.includes('data-qd-action="switch-api"'));
assert(markup.includes('data-qd-action="refresh-models"'));
console.log('V2.13-R1 QUICK DOCK CONSOLIDATION CHECKS: PASS');
